#pragma once

// button sprite dimensions and paths
#define BUTTON_SPRITES_H_DIMENSION 220
#define BUTTON_SPRITES_V_DIMENSION 200
#define BUTTON_SPRITESHEET_ROWS 1
#define BUTTON_SPRITESHEET_COLUMNS 2
#define BUTTON_SPRITESHEET_ROW_DIMENSION (BUTTON_SPRITES_H_DIMENSION * BUTTON_SPRITESHEET_ROWS)
#define BUTTON_SPRITESHEET_COLUMN_DIMENSION (BUTTON_SPRITES_V_DIMENSION * BUTTON_SPRITESHEET_COLUMNS)
#define BUTTON_SPRITESHEET_DIMENSION (BUTTON_SPRITESHEET_ROW_DIMENSION * BUTTON_SPRITESHEET_COLUMN_DIMENSION)
#define BUTTON_SPRITESHEET_SIZE (BUTTON_SPRITESHEET_DIMENSION * BUTTON_SPRITESHEET_DIMENSION)
#define BUTTON_SPRITESHEET_PATH "resources/sprites/buttons/"

// buttons locations, transform and animation
#define BUTTON_PRIMARY_X 150.0f
#define BUTTON_PRIMARY_Y 750.0f
#define BUTTON_PRIMARY_SCALE_X 0.7f
#define BUTTON_PRIMARY_SCALE_Y 0.7f
#define BUTTON_PRIMARY_ANIMATION_START_FRAME 0
#define BUTTON_PRIMARY_ANIMATION_END_FRAME 1
#define BUTTON_PRIMARY_ANIMATION_ROW 0
#define BUTTON_PRIMARY_ANIMATION_FRAME_TIME 0.1f
#define BUTTON_PRIMARY_ANIMATION_DIRECTION 0

#define BUTTON_SECONDARY_X 150.0f
#define BUTTON_SECONDARY_Y 680.0f
#define BUTTON_SECONDARY_SCALE_X 0.6f
#define BUTTON_SECONDARY_SCALE_Y 0.6f
#define BUTTON_SECONDARY_ANIMATION_START_FRAME 0
#define BUTTON_SECONDARY_ANIMATION_END_FRAME 1
#define BUTTON_SECONDARY_ANIMATION_ROW 0
#define BUTTON_SECONDARY_ANIMATION_FRAME_TIME 0.1f
#define BUTTON_SECONDARY_ANIMATION_DIRECTION 0