#define SPRITES_HORIZONTAL_DIMENSION 48
#define SPRITES_VERTICAL_DIMENSION 64
#define SPRITESHEET_ROWS 6
#define SPRITESHEET_COLUMNS 8
#define SPRITESHEET_ROW_DIMENSION (SPRITES_HORIZONTAL_DIMENSION * SPRITESHEET_ROWS)
#define SPRITESHEET_COLUMN_DIMENSION (SPRITES_VERTICAL_DIMENSION * SPRITESHEET_COLUMNS)
#define SPRITESHEET_DIMENSION (SPRITESHEET_ROW_DIMENSION * SPRITESHEET_COLUMN_DIMENSION)
#define SPRITESHEET_SIZE (SPRITESHEET_DIMENSION * SPRITESHEET_DIMENSION)
#define SPRITES_PATH "resources/sprites/"